name: azas
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.2+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.1.0
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path_ios: "assets/images/logo.jpg"
  image_path_android: "assets/images/logo.jpg"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
